// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3Vamu9zZciykTlo64e-wO-sSrDRoEDpo',
    appId: '1:630628051796:web:9b6e936ec9374e069676c1',
    messagingSenderId: '630628051796',
    projectId: 'nearyou-49d62',
    authDomain: 'nearyou-49d62.firebaseapp.com',
    databaseURL: 'https://nearyou-49d62.firebaseio.com',
    storageBucket: 'nearyou-49d62.appspot.com',
    measurementId: 'G-X8Q7GPNKLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFgOV1tpURO7jdJWP7rTQAaPfETsTgmr0',
    appId: '1:630628051796:android:c18d760aa51a33449676c1',
    messagingSenderId: '630628051796',
    projectId: 'nearyou-49d62',
    databaseURL: 'https://nearyou-49d62.firebaseio.com',
    storageBucket: 'nearyou-49d62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmkIBX8fF42iGIX-r504o2P5FAGFumjfI',
    appId: '1:630628051796:ios:87c308cef5fee57f9676c1',
    messagingSenderId: '630628051796',
    projectId: 'nearyou-49d62',
    databaseURL: 'https://nearyou-49d62.firebaseio.com',
    storageBucket: 'nearyou-49d62.appspot.com',
    androidClientId: '630628051796-r3sge1fnhsit8mhthh8n7eh7oh4si4o1.apps.googleusercontent.com',
    iosClientId: '630628051796-59r09qnkfrrdgdiunbind1ek91kn3vfq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chetneakV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmkIBX8fF42iGIX-r504o2P5FAGFumjfI',
    appId: '1:630628051796:ios:87c308cef5fee57f9676c1',
    messagingSenderId: '630628051796',
    projectId: 'nearyou-49d62',
    databaseURL: 'https://nearyou-49d62.firebaseio.com',
    storageBucket: 'nearyou-49d62.appspot.com',
    androidClientId: '630628051796-r3sge1fnhsit8mhthh8n7eh7oh4si4o1.apps.googleusercontent.com',
    iosClientId: '630628051796-59r09qnkfrrdgdiunbind1ek91kn3vfq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chetneakV2',
  );
}
